name: Update Database

on:
  push:
    branches: gh_actions #TODO: change this to cron when done

jobs:
  update_db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4
        with:
          path: edhtop16/

      - name: Checkout private library
        uses: actions/checkout@v4
        with:
          repository: EDH-Top-16/mtg_api
          token: ${{ secrets.MTG_API_PAT }}
          sparse-checkout: |-
            mtg_api.py
          sparse-checkout-cone-mode: false
          path: mtg_api/
          ref: main

      - name: Copy files to same working directory
        run: |-
          cp mtg_api/mtg_api.py edhtop16/server/scripts/
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Copy Secrets
        working-directory: edhtop16/server/scripts/
        run: |-
          echo "${{ secrets.TOPDECK_API_KEY }}" > eminence_api_key.txt
          echo "ATLAS_URI=${{ secrets.ATLAS_URI }}" > config.env

      - name: Run get_tournaments.py
        working-directory: edhtop16/server/scripts/
        run: python get_tournaments.py
      - name: Run get_commanders.py
        working-directory: edhtop16/server/scripts/
        run: python get_commanders.py

      - name: Copy Secrets
        working-directory: edhtop16/client/
        run:  |-
          echo 'ENTRIES_DB_URL="${{ secrets.ATLAS_URI }}"' > .env
          echo 'DATABASE_URL="${{ secrets.PSQL_CONN_STRING }}"' >> .env
      - name: Deploy 3nf db
        working-directory: edhtop16/client/
        run: npm run data-import -- --env-file=.env